### ISSUE TITLE
Adding contibutors list in the README.md file

### ISSUE THREAD

**Issue by anirudhsai20** [ucalyptus/Spotify-Recommendation-Engine#104]
The README.md file can be enhanced by adding a list of all the contributors along with their profile pics .

**Comment by anirudhsai20** [comment]
Hi. Please allow me to work on this issue under SWOC?

**Comment by forkbabu** [comment]
@anirudhsai20 the idea is great but I do not want to clutter the readme with this. That info is available already at https://github.com/ucalyptus/Spotify-Recommendation-Engine/graphs/contributors even with the amount of contribution they made to this.

Thanks for making this issue. Appreciate your interest.
