### ISSUE TITLE
make separate markdown file and transfer statistical techniques part there.

### ISSUE THREAD

**Issue by ucalyptus** [ucalyptus/Spotify-Recommendation-Engine#16]

**Comment by shreyateeza** [comment]
@ucalyptus Can you please elaborate what needs to be done. I would like to work on this issue.

**Comment by ucalyptus** [comment]
hi @shreyateeza https://github.com/ucalyptus/Spotify-Recommendation-Engine/pull/17 has been taken. Can you look at other issues?
