### ISSUE TITLE
Resize step images 

### ISSUE THREAD

**Issue by ucalyptus** [ucalyptus/Spotify-Recommendation-Engine#18]

**Comment by AnushkaH** [comment]
Hi, I'm interested to work on this

**Comment by HariniJeyaraman** [comment]
Hi, could you please provide a detailed description for this issue? I'm interested to work on this issue @ucalyptus

**Comment by Akansha2202** [comment]
Interested in this issue, please assign me this issue

**Comment by poojasrinivass** [comment]
I would like to work on this issue

**Comment by hritikpapa** [comment]
This seems easy, I have no experience in flutter but image processing is easy, I have done some work with PIL library also, if it is available and you find me worthy for this, then I can try to contribute to this project by taking this as my first issue.

**Comment by ucalyptus** [comment]
Not that complicated.
There are Steps on how to work with this in the README.
Resize the images  properly.

**Comment by manish-barnwal** [comment]
@ucalyptus I would like to contribute to this issue

**Comment by Mansi145** [comment]
Hey @ucalyptus what's the update on the issue? If the issue is up for taking, I'd like to work on this. 😄

**Comment by ucalyptus** [comment]
@Mansi145 sure. please do . we haven't had any PRs on this yet.

**Comment by Mansi145** [comment]
@ucalyptus do I only need to resize the images present in the README file?

**Comment by ucalyptus** [comment]
@Mansi145 yes
