### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by ucalyptus** [ucalyptus/Spotify-Recommendation-Engine#2]
- Fix broken image links
- Add emojis from http://emoji-cheat-sheet.com

**Comment by marfgold1** [comment]
Hello, I would like to fix this!

**Comment by debjeet06** [comment]
Hello , I would like to work on this.

**Comment by biswaroop1547** [comment]
i am done with this

**Comment by marfgold1** [comment]
Can I make the readme more better and readable? It's still lack of emojis and broken images.

**Comment by biswaroop1547** [comment]
@ucalyptus i've fixed the broken image links on #3
