### ISSUE TITLE
Flutter clone of Spotify

### ISSUE THREAD

**Issue by ucalyptus** [ucalyptus/Spotify-Recommendation-Engine#24]
A clone is a non-copyrighted free version of a real application.
Here is an example of how [Instagram was cloned](https://www.youtube.com/watch?v=E2uEfOls4e4)
cc: @TanishaSingh16

**Comment by TanishaSingh16** [comment]
> yes

**Comment by ucalyptus** [comment]
@TanishaSingh16 you can go ahead and create a clone of Spotify. I am in talks with other flutter devs on how to go ahead with that and  if copyright issues might come up in the flutter. Feel free to ask anything about this project.

**Comment by ucalyptus** [comment]
@TanishaSingh16 follow these:
- [ ] Fork the project
- [ ] In your forked project create a branch called tanisha-flutter-branch
- [ ] App contents go into that branch
- [ ] Make a Pull Request **not with master** branch of mine but with **flutter** branch.

**Comment by ucalyptus** [comment]
Update: No copyright issues will happen.

**Comment by Rishabh510** [comment]
I would like to work on this. Starting from this one #32

**Comment by ucalyptus** [comment]
> I would like to work on this. Starting from this one #32

go ahead.

**Comment by ucalyptus** [comment]
Folks, comment here to get assigned to this issue. This issue can be assigned to multiple people as we choose the best UI out of all.

**Comment by joardar-aditya** [comment]
Working on the flutter app already! please assign me this issue!

**Comment by ucalyptus** [comment]
@joardar-aditya done

**Comment by ShekarMudaliyar** [comment]
i'd like to work on this issue

**Comment by payal-98** [comment]
I would like to work on this.

**Comment by AjinkyaTaranekar** [comment]
Hello Sir, I would like to work on this issue.

**Comment by Rishabh510** [comment]
Hello, could you please check out this branch and tell me what I should do next. 
https://github.com/Rishabh510/Spotify-Recommendation-Engine/blob/spotify_mockup/spotify_mockup/README.md

**Comment by algokun** [comment]
hey, i'm willing to work on this issue. Is this available now?

**Comment by ucalyptus** [comment]
@AbhilashG97 feel free to comment.

**Comment by AbhilashG97** [comment]
Hello @Rishabh510, 

We have chosen a mockup for this project and the same can be found [here](https://github.com/ucalyptus/Spotify-Recommendation-Engine/tree/flutter). 

You have to work on the flutter app now by following the mockup. Please note that we already have a flutter branch in our project, so please create your own branch from the flutter branch before working on this issue.

If you have any questions, please let us know. I'm sorry for the delay in my reply, please excuse me.

**Comment by AbhilashG97** [comment]
@algokun, yes you may proceed.

**Comment by Rukmini-Meda** [comment]
@AbhilashG97 I would like to work on this issue. Please assign this to me as part of GSSoC'20

**Comment by ucalyptus** [comment]
@Rukmini-Meda as announced on slack, no explicit assigning is required. Just go ahead with it, waiting for a pull request from you.

**Comment by Rukmini-Meda** [comment]
I think there can be multiple issues for this. The entire app development can be made into multiple issues. That will be easy to monitor as well. What do you say @ucalyptus ?

**Comment by ucalyptus** [comment]
@AbhilashG97 will have a better answer.

**Comment by preeti13456** [comment]
Git clone you are talking about ? Or what we can do is add our own mockup and animation and change it and make it more interesting.
