### ISSUE TITLE
Refactor notebook

### ISSUE THREAD

**Issue by ucalyptus** [ucalyptus/Spotify-Recommendation-Engine#27]
Refactor notebook into a set of python files. Follow PEP8 Guidelines. Use flake8 for linting and Black for code-formatting.

**Comment by amoghjalan** [comment]
I would like to work on this.

**Comment by vipuldcoder** [comment]
I am interested with the issue.

**Comment by preeti13456** [comment]
Interested

**Comment by HariniJeyaraman** [comment]
Please @ucalyptus assign me this issue.

**Comment by Akansha2202** [comment]
I'm interested in this issue

**Comment by ucalyptus** [comment]
@amoghjalan @vipuldcoder @preeti13456 @HariniJeyaraman have been assigned but no PRs as of yet received

**Comment by amoghjalan** [comment]
> @amoghjalan @vipuldcoder @preeti13456 @HariniJeyaraman have been assigned but no PRs as of yet received

Sorry @ucalyptus , I had refactored them just couldn't make PR then
