### ISSUE TITLE
Inclusion of login/signup dependency for Flutter clone

### ISSUE THREAD

**Issue by Rishabh510** [ucalyptus/Spotify-Recommendation-Engine#29]
## Provide a login/signup dependency for Flutter clone of Spotify.

Any of the following:
1. REST API
2. Firebase
3. Spotify package (https://pub.dev/packages/spotify)

**Comment by ucalyptus** [comment]
@Rishabh510 https://github.com/rinukkusu/spotify-dart
Can this be implemented ?

**Comment by ucalyptus** [comment]
@Rishabh510 push changes to flutter branch only . not master 
https://github.com/ucalyptus/Spotify-Recommendation-Engine/tree/flutter

**Comment by Rishabh510** [comment]
> @Rishabh510 push changes to flutter branch only . not master
> https://github.com/ucalyptus/Spotify-Recommendation-Engine/tree/flutter

OK👍 So should I create another branch in my fork or make changes in the flutter branch itself?

**Comment by Rishabh510** [comment]
> @Rishabh510 https://github.com/rinukkusu/spotify-dart
> Can this be implemented ?

I'll have to test it out before confirming anything as this package has been released only a week ago so errors are bound to exist.

**Comment by ucalyptus** [comment]
> > @Rishabh510 https://github.com/rinukkusu/spotify-dart
> > Can this be implemented ?
> 
> I'll have to test it out before confirming anything as this package has been released only a week ago so errors are bound to exist.

Ok

**Comment by ucalyptus** [comment]
> > @Rishabh510 push changes to flutter branch only . not master
> > https://github.com/ucalyptus/Spotify-Recommendation-Engine/tree/flutter
> 
> OK+1 So should I create another branch in my fork or make changes in the flutter branch itself?

create a branch in ur fork from upstream's flutter branch and create a PR onto it.

**Comment by joardar-aditya** [comment]
Having checked the spotify authorisation documentation. The implicit grant method flow would be the best for an application i guess. Where we can request for a token by redirecting the user from the app to the spotify website and then getting back the web credentials in the app! 
Can this be done?

**Comment by Potential17** [comment]
Hey,
I would like to work on this.

**Comment by ucalyptus** [comment]
Updates @joardar-aditya and @Potential17 ?

**Comment by joardar-aditya** [comment]
What is the final ui decided for the app?

**Comment by ucalyptus** [comment]
@AbhilashG97 feel free to comment.

**Comment by Potential17** [comment]
Kindly allow some more time,
Will present it to you by this week.

**Comment by ucalyptus** [comment]
@Potential17 any updates?

**Comment by Potential17** [comment]
https://github.com/Potential17/Flutter-app
Just some minors to fix

**Comment by ucalyptus** [comment]
awaiting a PR. only way i can review

**Comment by Potential17** [comment]
sure

**Comment by Rukmini-Meda** [comment]
I would like to work on this issue if its not done. Please assign this to me as part of GSSoC'20. I can make PR early

**Comment by Potential17** [comment]
@ucalyptus A PR created yesterday already.
Check it.
