### ISSUE TITLE
Improve README

### ISSUE THREAD

**Issue by ucalyptus** [ucalyptus/Spotify-Recommendation-Engine#30]
Currently README requires some improvements to improve visual inspection of all details for new beginners.
Suggest some UI changes in the this issue thread and mention your github id as @{id} . Will assign issues as required.

**Comment by ucalyptus** [comment]
Comment here if you want to take this up

**Comment by infiniteoverflow** [comment]
I would like to take this up for the Gssoc Contribution :)

**Comment by annu12340** [comment]
I also would like to work on this issue

**Comment by Akansha2202** [comment]
please assign me this isssue

**Comment by ashishbinu** [comment]
I would like take up this issue

**Comment by bhushanyadav07** [comment]
I'm Interested please assign me this **_issue_** :)

**Comment by SaraLatif99** [comment]
Is this still open? Cana you please assign it to me?
