### ISSUE TITLE
Create mockups for the Flutter mobile app

### ISSUE THREAD

**Issue by AbhilashG97** [ucalyptus/Spotify-Recommendation-Engine#32]
The project requires a mobile app. However, there are no mockups for the app. Please create mockups for the app. 

You have to create UI for the following activities - 
1. Login
1. Home
1. Your Library (for recommendations)
1. Settings

**Note**: Attach the mockups in a folder called ```Mockups``` in the root directory of the project and then send a pull request.  You **can use any prototyping tool** of your choice. A few good ones are [Adobe XD](https://www.adobe.com/in/products/xd.html), [Balsamiq](https://balsamiq.com/). 

:exclamation: Please don't create an actual app while working on the issue, you supposed to create a rough design of how the app should look like. 

:warning: The best mockup will be selected and the app's UI will be based on that mockup.

**Comment by Samriddhi25** [comment]
I would like to work on this.

**Comment by AbhilashG97** [comment]
@Samriddhi25 you may proceed to work on this issue.

**Comment by AbhilashG97** [comment]
**Note:** This issue is open to all.

**Comment by ucalyptus** [comment]
**NOTICE**
Multiple assignees allowed on this issue

**Comment by algokun** [comment]
Hello, i would like to work on this.

**Comment by Potential17** [comment]
Hey,I would like to work on this.

**Comment by joardar-aditya** [comment]
Hello , i would like to work on this!

**Comment by preeti13456** [comment]
Interested to work on it.

**Comment by ucalyptus** [comment]
@AbhilashG97 assign the participants

**Comment by HariniJeyaraman** [comment]
Hi, participant of GSSoC 2020 here. Interested to work on this issue. Please assign me @ucalyptus

**Comment by algokun** [comment]
I'm about to complete the whole ui. Could you please assign the task to me @ucalyptus @AbhilashG97

**Comment by Rishabh510** [comment]
Hello @AbhilashG97 , i've already made PR #36 regarding this. And I haven't been assigned this. Please assign me and also take a look at the fore mentioned PR.

**Comment by ucalyptus** [comment]
@Rishabh510 Thanks for the PR. @AbhilashG97 will review it soon.

**Comment by ShekarMudaliyar** [comment]
i'd like to work on this issue

**Comment by ucalyptus** [comment]
**ANNOUNCEMENT:**
Here is the workflow to contribute ur PR against this issue:

1. Do not create the actual UI of the app, create a mockup. Mockups can be created using prototyping tools like Adobe XD, Balsamiq etc.
2. Actual Screenshots be kept in a drive or onedrive folder and shared in the comment thread tagging @ucalyptus or @AbhilashG97 . 
3. You will be assigned a reviewer among the mentors.
4. Mention the tool(s) you used to create the mockups.

**Reason for not creating actual UI**
We already have participants working on the actual app. We won't need the whole app just for the mockup.

cc'ing this to the slack as well.
cc: @Rishabh510 since you and some other participants have created the actual ui, follow step 2.
cc: @AbhilashG97

**Comment by algokun** [comment]
🚀 My Prototype is live and you can see it here : https://www.figma.com/proto/9f6XCJdgtsUraJ79tIhd5F/Spotify-Redesign?node-id=1%3A2&viewport=1059%2C-456%2C1&scaling=scale-down

**Comment by algokun** [comment]
@AbhilashG97 could you please review my pr
https://github.com/ucalyptus/Spotify-Recommendation-Engine/pull/41

**Comment by Rishabh510** [comment]
> **ANNOUNCEMENT:**
> Here is the workflow to contribute ur PR against this issue:
> 
> 1. Do not create the actual UI of the app, create a mockup. Mockups can be created using prototyping tools like Adobe XD, Balsamiq etc.
> 2. Actual Screenshots be kept in a drive or onedrive folder and shared in the comment thread tagging @ucalyptus or @AbhilashG97 .
> 3. You will be assigned a reviewer among the mentors.
> 4. Mention the tool(s) you used to create the mockups.
> 
> **Reason for not creating actual UI**
> We already have participants working on the actual app. We won't need the whole app just for the mockup.
> 
> cc'ing this to the slack as well.
> cc: @Rishabh510 since you and some other participants have created the actual ui, follow step 2.
> cc: @AbhilashG97

As mentioned by you, here are the screenshots of the actual app that I created. https://drive.google.com/open?id=1K30i6UtrwukmHjR6_lQ0ARNLQIJn7NHJ

PS: Sorry for misunderstanding, I started working on #24 even before this issue was created and directly built the UI without creating mockups.
