### ISSUE TITLE
Implementing the recommender system using K Means Clustering and merging my Spotify dataset(18836 rows) to the current one.

### ISSUE THREAD

**Issue by BALaka-18** [ucalyptus/Spotify-Recommendation-Engine#35]
I wish to enhance the current model by :
1. Adding more data(18836 more) to the current dataset of 50 rows. More data will help this project by providing better analytical insights and a stronger model.
2. Add dataset of artists to extend the recommendation model to artists too.
3. Add to the current model by implementing collaborative filtering using K Means Clustering.

**Comment by Shubham-1105** [comment]
I am interseted for ths issue

**Comment by ucalyptus** [comment]
@BALaka-18 @Shubham-1105 check out this issue https://github.com/ucalyptus/Spotify-Recommendation-Engine/issues/7

**Comment by Akansha2202** [comment]
I'm interested in this issue

**Comment by poojasrinivass** [comment]
I would like to work on this issue

**Comment by mohdwasi03** [comment]
i have collected some data for dataset assign me that issue to work on it.

**Comment by ucalyptus** [comment]
@mohdwasi03 done

**Comment by ucalyptus** [comment]
@poojasrinivass @mohdwasi03 @Shubham-1105 @Akansha2202 @BALaka-18 no pull requests received on this issue. Closing this in 1 day.

**Comment by Akansha2202** [comment]
from where to get the dataset?

**Comment by jmuskaan72** [comment]
I would like to work on this issue.

**Comment by yugaljain1999** [comment]
I would like to work on this issue
