### ISSUE TITLE
PR checker using Github Actions.

### ISSUE THREAD

**Issue by ucalyptus** [ucalyptus/Spotify-Recommendation-Engine#40]
- [ ] Code Styling bot
- [ ] flake8 testing utility for Python or Jupyter files.
- [ ] black code-formatting for the above.

**Comment by ucalyptus** [comment]
@AbhilashG97 any additions to this? 
Participants who have worked with and are interested in CI/CD and Github Actions can contribute in the thread below.

**Comment by Rishabh510** [comment]
I have a little experience with GitHub actions. I would like to take up this issue, but will only be able to work in and after 8th March dur to exams.

**Comment by ucalyptus** [comment]
@Rishabh510 you are most welcome

**Comment by ucalyptus** [comment]
https://githubhackathon.com/#hackathon

**Comment by Rishabh510** [comment]
Hello, my exams just got over. I am ready to work on this issue.

**Comment by Rishabh510** [comment]
> * [ ]  Code Styling bot
> * [ ]  flake8 testing utility for Python or Jupyter files.
> * [ ]  black code-formatting for the above.

Could you please guide me exactly what you want the action to do. Thank you!

**Comment by ucalyptus** [comment]
Rishabh I want the action to check pr branch for python files and perform flake8 tests to ensure code is upto Codacy standards and follows the PEP8 guidelines. Will add more as we go into this.

**Comment by Rishabh510** [comment]
I don't know about Codacy and how it works. Also, can I get some help regarding this issue. I've at the moment only created workflows that use Flutter.

**Comment by ucalyptus** [comment]
@Rishabh510 don't worry about Codacy. You can make a PR with whatever you completed.

**Comment by ucalyptus** [comment]
@Rishabh510  #47 is a perfect example of what was needed. Closing this
