### ISSUE TITLE
I would like to work on the integration part. How to integrate python with android studio. Also can we make a web app using flask?

### ISSUE THREAD

**Issue by priyanka2109** [ucalyptus/Spotify-Recommendation-Engine#45]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by ucalyptus** [comment]
Fill the template with details of your feature request

**Comment by payal-98** [comment]
I would like to work on this issue

**Comment by ucalyptus** [comment]
This issue is out of scope of our project.
