### ISSUE TITLE
Github Actions for monitoring this project 

### ISSUE THREAD

**Issue by mySTRiouscoder** [ucalyptus/Spotify-Recommendation-Engine#47]
I'm planning to add following actions to this project:
1.)Greet:This action will greet the participant whenever they raise an issue or submit a PR .
2.)Stale: To mark unattended issues or PR(s).
3.)Mind-Your-Language: To warn the participant if he/she uses foul language in the reposiotry

Working on this ? Yes!

**Comment by ucalyptus** [comment]
Add more if possible . Great work done

**Comment by mySTRiouscoder** [comment]
> Add more if possible . Great work done

Ya sure. Thanks.
