### ISSUE TITLE
Beginner Issue [GSSOC20] : Add contributors names to the README

### ISSUE THREAD

**Issue by ucalyptus** [ucalyptus/Spotify-Recommendation-Engine#64]
- Check out the Closed PR list and see which ones were merged.
- According to easy, medium and hard or beginner , sort them out 
- Mention their github id , their PR or PRs beside them.
- Add them to the README.
- Only add contributors whose PRs have [gssoc20] labels.

**Comment by chttrjeankr** [comment]
Would like to take this up. :slightly_smiling_face:

**Comment by ucalyptus** [comment]
send a pr

**Comment by Amitsharma45** [comment]
@ucalyptus  i would like to work on this issue please assigm this issue  to me

**Comment by ucalyptus** [comment]
Send a pr. I would say this to all people who are interested.
