### ISSUE TITLE
Implicit Matrix Factorisation

### ISSUE THREAD

**Issue by ucalyptus** [ucalyptus/Spotify-Recommendation-Engine#7]
- [x] Implement this [paper](https://github.com/ucalyptus/Spotify-Recommendation-Engine/files/4246611/he2016.pdf) . Video on the math Coming Soon
- [x] Code to paper is [here](https://github.com/hexiangnan/sigir16-eals) 
- [x] Port the implementation to Python from Java 
- [x] Amazon Rating Dataset . [Link here](https://drive.google.com/file/d/1h4eU_WNzL-FHYJ5n-D3YY6ItAhB-REQ0/view?usp=sharing)

**Comment by prateekmaj21** [comment]
@prateekmaj21

**Comment by ucalyptus** [comment]
@prateekmaj21 https://github.com/thedatastreet/CBRS

**Comment by tista123** [comment]
Can I work on this issue?

**Comment by ucalyptus** [comment]
Check this paper . We are planning to implement this. 
[he2016.pdf](https://github.com/ucalyptus/Spotify-Recommendation-Engine/files/4246611/he2016.pdf)

**Comment by ka1shi** [comment]
Hi @ucalyptus, I would like to work on this issue.

**Comment by SubhradeepSS** [comment]
@ucalyptus would like to work on the issue

**Comment by Shubham-1105** [comment]
I am also interested to work on this isssue as well

**Comment by ucalyptus** [comment]
I have added the dataset link as well.

**Comment by ka1shi** [comment]
@Shubham-1105 @SubhradeepSS, Can we connect on slack, so we can better decide how we should proceed ahead?

**Comment by Shubham-1105** [comment]
Yes

**Comment by SubhradeepSS** [comment]
> @Shubham-1105 @SubhradeepSS, Can we connect on slack, so we can better decide how we should proceed ahead?

Sure

**Comment by poojasrinivass** [comment]
I would like to work on this issue as well.

**Comment by aanagran** [comment]
hii @ucalyptus, i would like to work on this issue.
can you assign me this issue?

**Comment by tripathyprateek** [comment]
@ucalyptus I would like to be assigned this task. I have worked on the Spotify API before, and I would be able to complete this  task.

**Comment by lucky-suman** [comment]
I will help for this issue, as I worked before on Implicit recommendation systems earlier.

**Comment by ucalyptus** [comment]
hi @lucky-suman check slack DM

**Comment by priyanka2109** [comment]
I would like to work on this issue.

**Comment by ayushbathrey** [comment]
I would like to be assigned this task.

**Comment by Shubhangipanda** [comment]
Hi! I would like to work on this issue.

**Comment by ayushbathrey** [comment]
Join this group for discussion https://chat.whatsapp.com/BXCzibZ5eCS9sYBTkXJitW

**Comment by ucalyptus** [comment]
@lucky-suman join

**Comment by Shubhangipanda** [comment]
Hi! I would like to work on this issue.

**Comment by maheshwari-git** [comment]
can lsuman@redhat.com be unsubscribed from this repo notifications ? @lucky-suman

**Comment by ucalyptus** [comment]
@maheshwari-git did not get you

**Comment by ucalyptus** [comment]
- A. Would be great if you folks divide the work of porting into python among yourselves. 
A.1 Use the toy Amazon Rating Dataset
A.2 What I meant by dividing the work is you need to refactor the code i.e 
break the code down to multiple files each serving a specific purpose. Eg. utils.py,init.py,dataset.py , train.py etc
A.3 Push your PRs not to master but to research branch
A.4 Feel free to reach out to me on Slack or Lucky Suman who is a mentor for our project. Lucky is an ex-data scientist at Red Hat and has worked on RecSys plugins for RedHat on VS-Code.
A.5 For recommendation systems there are many algorithms available but few cater to dynamic settings. A platform like Spotify is dynamic where users are daily added, removed. Users interact with new songs and unlike old songs etc. We as a human are a subject of an online learning setting. In such situations model has to be refreshed or reweighted (think how boosting algorithms work by learning from the predecessor) .
A.6 Read the paper thoroughly to understand why normal algorithms cannot mimic the case with Spotify
-  B. Once we finish working with the toy dataset, me and the mentors will work with the Flutter team for their status on the UI and backend.
B.1 In this stage , we know that the algorithm works but we need a dynamic setting now.
B.2 There can be two ways to create a dynamic setting , 
a. we make a playlist locally and recommendations are based on this . All existing songs and suggested songs will exist in local storage of the user. 
b. We create a live example. User signs into his Spotify Account(OAuth capabilities needed), spotipy api reads his playlist. We get a User Interaction Matrix from the API. The U-I matrix and its artifacts (because dyanmic setting) are fed into the implicit MF model (created in Phase A) and we fetch the created playlist(suggested by our model) into the Flutter App. 
Direction b is simpler to think since we have a notebook implemented in this direction existing (in the master branch).
-  This is a two phase project for the two months remaining for GSSOC.
- More or less this will be the frame of work. Some edits will be made after consultation with other mentors and data scientists and app devs.

**Comment by salonipriyani** [comment]
Interested!

**Comment by ucalyptus** [comment]
**No longer taking any more assignees**

**Comment by ucalyptus** [comment]
> Join this group for discussion https://chat.whatsapp.com/BXCzibZ5eCS9sYBTkXJitW
This is optional however you can ask me more here

**Comment by yugaljain1999** [comment]
Please assign me this issue @ucalyptus .

**Comment by ucalyptus** [comment]
@yugaljain1999 as announced on slack, no explicit assigning is required. Just go ahead with it, waiting for a pull request from you.

**Comment by luckysuman03** [comment]
Hello guys, any update on this. Please let me know if anybody needs any help in terms of code and algorithm. As real-time data generally is skewed, so would suggest going for HPF(Hierarchical Poisson Factorization). 
For more information: https://github.com/david-cortes/hpfrec
