### ISSUE TITLE
autosquash gh actions not working as github token missing

### ISSUE THREAD

**Issue by ucalyptus** [ucalyptus/Spotify-Recommendation-Engine#72]
Run tibdex/autosquash@v21s
##[error]Input required and not supplied: github_token

**Comment by ucalyptus** [comment]
Take cues from https://github.com/ucalyptus/Spotify-Recommendation-Engine/runs/674579159?check_suite_focus=true

**Comment by preeti13456** [comment]
Interested

**Comment by preeti13456** [comment]
We can  Add this
 - uses: tibdex/autosquash@v2 
   with: 
     # We can't use the built-in secrets.GITHUB_TOKEN yet because of this limitation: 
     # https://github.community/t5/GitHub-Actions/Triggering-a-new-workflow-from-another-workflow/td-p/31676 
     # In the meantime, use a personal access token with repo access. 
     # See https://help.github.com/en/articles/creating-a-personal-access-token-for-the-command-line 
     github_token: ${{ secrets.AUTOSQUASH_TOKEN }}
