### ISSUE TITLE
Repair README.md

### ISSUE THREAD

**Issue by ucalyptus** [ucalyptus/Spotify-Recommendation-Engine#74]
README.md needs an urgent fix.
Figure out the last commit on README.md and restore the contents that were involved.

**Comment by vyom153069** [comment]
please assign this issue to me , i am a begginer

**Comment by CodeSadhu** [comment]
If nobody's assigned, I'd like to do this.

**Comment by ucalyptus** [comment]
Don't wait for assignments
. Go ahead with a PR

**Comment by CodeSadhu** [comment]
@ucalyptus Okay. All I need to do is restore the current README.md with an older copy right? The one where it was fine?

**Comment by CodeSadhu** [comment]
@ucalyptus Okay. All I need to do is restore the current README.md with an older copy right? The one where it was fine?

**Comment by ucalyptus** [comment]
Right

**Comment by CodeSadhu** [comment]
@ucalyptus PR sent.
