### ISSUE TITLE
RecSys from scratch

### ISSUE THREAD

**Issue by ucalyptus** [ucalyptus/Spotify-Recommendation-Engine#8]

**Comment by jaindhairyahere** [comment]
Can I work on this?

**Comment by ucalyptus** [comment]
sure

**Comment by jaindhairyahere** [comment]
how to get started?
I mean the dataset, and what kind of Matrix Factorization should I use

**Comment by ucalyptus** [comment]
Implicit Matrix Factorization.
To get the dataset you need to use the Spotify API
