### ISSUE TITLE
Improve README

### ISSUE THREAD

**Issue by forkbabu** [ucalyptus/Spotify-Recommendation-Engine#83]

**Comment by M-PRERNA** [comment]
Can you assign this issue to me, I am a SWOC participant.

**Comment by ucalyptus** [comment]
All issues are open to all. Please make a PR and tag me.

**Comment by M-PRERNA** [comment]
Sure, I'll be making the PR soon.

**Comment by M-PRERNA** [comment]
I had a doubt. Do I need to make a PR to get this issue assigned to me?

**Comment by sidhu1012** [comment]
> I had a doubt. Do I need to make a PR to get this issue assigned to me?

You have claimed this issue by commenting. Open a PR to fix it.

**Comment by M-PRERNA** [comment]
Ok sure!

**Comment by Avinash-1501** [comment]
I tried adding some interactivity to readme page. Now in the 'steps to follow' section, only the main points are visible, and the extra info is under collapse. Can I make a PR with this. Preview the changes i've made here: https://github.com/Avinash-1501/Spotify-Recommendation-Engine/blob/master/README.md and please suggest if can do any modifications or extra changes.

**Comment by ucalyptus** [comment]
@Avinash-1501 also make a table fr swoc contributors, and shift all other soc programs to the very end of the readme since swoc is our highlight.
