### ISSUE TITLE
Add an SWOC: Important Links Section to README

### ISSUE THREAD

**Issue by forkbabu** [ucalyptus/Spotify-Recommendation-Engine#84]

**Comment by M-PRERNA** [comment]
is this issue still open?

**Comment by sidhu1012** [comment]
> is this issue still open?

Yes.

**Comment by M-PRERNA** [comment]
I would like to work on it !!! please assign it to me.

**Comment by sidhu1012** [comment]
> I would like to work on it !!! please assign it to me.

You have it. Commenting is enough to claim. Start working!

**Comment by M-PRERNA** [comment]
Sure!

**Comment by Avinash-1501** [comment]
Do we need to add SWOC website link to the readme?

**Comment by sidhu1012** [comment]
> Do we need to add SWOC website link to the readme?

Yes I think it should be there.
