### ISSUE TITLE
PCA+SVM instead of the current recommendation engine

### ISSUE THREAD

**Issue by forkbabu** [ucalyptus/Spotify-Recommendation-Engine#85]
- Colab link needed.

**Comment by M-PRERNA** [comment]
what exactly has to be done in this issue?

**Comment by forkbabu** [comment]
Hi @M-PRERNA , in this project you have to implement the recommendation system . Specifically, you have to change the algorithms given here in https://github.com/ucalyptus/Spotify-Recommendation-Engine/blob/master/Spotify_Recommendation_System_.ipynb

**Comment by M-PRERNA** [comment]
ohkay

**Comment by forkbabu** [comment]
@M-PRERNA any progress?

**Comment by M-PRERNA** [comment]
Ah, actually I am not aware of how to change the algorithms! I would need some guidance in that.

**Comment by forkbabu** [comment]
Hi there @M-PRERNA , please DM me on the slack.

**Comment by SinghShreya05** [comment]
@forkbabu Is this issue still open? I'll like to work on it, can you please assign me?

**Comment by ucalyptus** [comment]
@SinghShreya05 go ahead with a PR.

**Comment by SinghShreya05** [comment]
https://colab.research.google.com/drive/1IzDrrMQ0ZtvNsCXRc_4a6ELJNaRUtILl?usp=sharing @forkbabu 
this is colab, I had made some typos, pushed the corrected code with the changes, please review the PR
