### ISSUE TITLE
Embed the YT video on README instead of hyperlink

### ISSUE THREAD

**Issue by ucalyptus** [ucalyptus/Spotify-Recommendation-Engine#91]

**Comment by Aayush-hub** [comment]
@ucalyptus Sir, Can u please assign me this? #SWOC

**Comment by ucalyptus** [comment]
Issues are open and never assigned. People interested should come up with a PR and tag me.

**Comment by Avinash-1501** [comment]
@ucalyptus I've read that, there is no such feature supported by github flavoured markdown to directly embed a youtube video in readme. Instead we can place a youtube thumbnail of that video and attach the youtube link to that picture. Is this what we've to do? Or we can directly embedd a video in readme?

**Comment by ucalyptus** [comment]
If embedding is not an option , a thumbnail would do. Much better option that just a simple link.
