### ISSUE TITLE
A working prototype of the Flutter Frontend

### ISSUE THREAD

**Issue by forkbabu** [ucalyptus/Spotify-Recommendation-Engine#95]
- Test the "Flutter-App" contents. Those are 8 months old. Not tested since then.
- Contact the PA regarding the test results.
- After discussions, move forward to a working implementation of the Spotify clone on Flutter.

**Comment by HimeshNayak** [comment]
Since the code contains bugs I can debug it for a working app code and after that #96 can be started. Please assign this task to me.

**Comment by forkbabu** [comment]
@HimeshNayak any updates on this?
