### ISSUE TITLE
Creating the flutter app according to provided UI/UX

### ISSUE THREAD

**Issue by hareshnayak** [ucalyptus/Spotify-Recommendation-Engine#96]
Please assign me the issue for creating the UI and the screen navigation of the app under SWOC 2021

**Comment by forkbabu** [comment]
Acknowledged. @hareshnayak .

**Comment by forkbabu** [comment]
# Note *Issue is still open to others. Only a merged PR is evaluated as a contribution, till then it is open to all.*

**Comment by Neha62-lit** [comment]
I would like to work on this issue.. Can you assigned me this issue???

**Comment by ucalyptus** [comment]
@Neha62-lit feel free to make a PR.  I will be active on Github from 12th jan

**Comment by Neha62-lit** [comment]
@ucalyptus Okay sir. Thank you!

**Comment by forkbabu** [comment]
@hareshnayak any updates?

**Comment by Vrushti24** [comment]
Is this still open ?

**Comment by forkbabu** [comment]
@Vrushti24 yes it is.

**Comment by forkbabu** [comment]
@Vrushti24 backend code is yet to be written. #101 was on the mockups and frontend.

**Comment by Vrushti24** [comment]
Okay frontend is done okay

**Comment by Vrushti24** [comment]
I wanted to work on frontend
