### ISSUE TITLE
Github Action workflows for Flutter.

### ISSUE THREAD

**Issue by forkbabu** [ucalyptus/Spotify-Recommendation-Engine#98]

**Comment by hpnightowl** [comment]
can i take this issue? as the part of SWOC?

**Comment by forkbabu** [comment]
Sure

**Comment by forkbabu** [comment]
@hpnightowl has to be done in the app branch of the repo where flutter code will reside and can be only done when https://github.com/ucalyptus/Spotify-Recommendation-Engine/pull/97 is merged.

**Comment by hpnightowl** [comment]
ok i will keep and eye on that PR as soon as it will be merged i will PR github action

**Comment by ucalyptus** [comment]
@hpnightowl you can go ahead now.

**Comment by ucalyptus** [comment]
@hpnightowl remove these workflows first
https://github.com/ucalyptus/Spotify-Recommendation-Engine/tree/app/.github/workflows

**Comment by hpnightowl** [comment]
ok

**Comment by hpnightowl** [comment]
@ucalyptus but those workflows are not needed now? I can see it was updated 4 hours ago

**Comment by ucalyptus** [comment]
The app branch doesn't need these workflows.

**Comment by hpnightowl** [comment]
ohk and github action should release the test build also or only for checks?

**Comment by hpnightowl** [comment]
ping me any more changes are needed and what was expected I will correct it thanks since there were some doubts like we need to build apk also in check ? , and workflow should work for pull request and push (I made for both).

**Comment by ucalyptus** [comment]
There are so many things involved. I will contact you on Monday. A bit busy.

**Comment by hpnightowl** [comment]
ok !
